### ISSUE TITLE
NoClassDefFoundError jayway/jsonpath/Predicate

### ISSUE THREAD

**Issue by martipello** [algolia/instantsearch.js#2895]
just started getting this error this morning using the most recent version 
java.lang.NoClassDefFoundError: Failed resolution of: 
[Lcom/jayway/jsonpath/Predicate;     
at com.algolia.instantsearch.utils.JSONUtils.getObjectFromJSONPath(JSONUtils.java:40)
at com.algolia.instantsearch.utils.JSONUtils.getStringFromJSONPath(JSONUtils.java:22)
at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:473)
at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:409)

**Comment by Haroenv** [comment]
Hey @martipello, seems like you're using Java, I opened an issue for you in the correct repository, feel free to comment there: https://github.com/algolia/instantsearch-android/issues/76
