### ISSUE TITLE
Build fails on Node.js 14.15

### ISSUE THREAD

**Issue by tnir** [algolia/instantsearch.js#4639]
## 🐛 Bug description

Build fails on Node.js 14.15

## 🔍 Bug reproduction

```
$ git clone ...
$ yarn
[...]
$ yarn build
yarn run v1.22.10
$ yarn run build:cjs && yarn run build:es && yarn run build:umd
$ rm -rf cjs && BABEL_ENV=cjs babel src --extensions '.js,.ts,.tsx' --out-dir cjs/ --ignore 'src/index.es.ts','**/__tests__','**/__mocks__' --quiet
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /workspace/instantsearch.js/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/workspace/instantsearch.js/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ node --version
v14.15.4
$ npm --version
7.5.2
```

**Comment by Haroenv** [comment]
Yes, we still need to update babel with the latest version (that doesn't have this bug), but in the mean time if you do `nvm use` (or use node 12) in the directory before building it should be all fine.
